# S3 config
S3_URL = "YOUR_S3_HOST_URL"
S3_KEY = "YOUR_S3_KEY"
S3_SECRET = "YOUR_S3_SECRET"
BUCKET_NAME = "YOUR_S3_BUCKET_NAME"


# OIDC config
OIDC_ISSUER = "YOUR_OIDC_ISSUER"
OIDC_CLIENT_CONFIG = "YOUR_OIDC_CLIENT_CONFIG"
