"""Add Files and Harold Tables

Revision ID: 4d90006338cd
Revises: 4d4d50316342
Create Date: 2022-03-26 04:11:41.457277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d90006338cd'
down_revision = '4d4d50316342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harolds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harolds')
    op.drop_table('files')
    # ### end Alembic commands ###
